import { Button, HorizontalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "ReGuilded Installer";
    icon: @image-url("../data/icon.png");

    GridLayout {
        Row {
            HorizontalBox {
                Button { text: "First"; }
                Button { text: "Second"; }
                Button { text: "Third"; }
            }
        }

        Row {
            HorizontalBox {
                Button {
                    text: "Click Me";
                    clicked => { self.text = "I was clicked!"}
                }
            }
        }
    }
}